-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.organization
(
    organization_id serial NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    contact_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    logo_filename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT organization_pkey PRIMARY KEY (organization_id)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    project_id serial NOT NULL,
    title character varying(250) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    location character varying(250) COLLATE pg_catalog."default" NOT NULL,
    date date NOT NULL,
    organization_id integer NOT NULL,
    CONSTRAINT projects_pkey PRIMARY KEY (project_id)
);

ALTER TABLE IF EXISTS public.projects
    ADD FOREIGN KEY (organization_id)
    REFERENCES public.organization (organization_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

SELECT * FROM projects;

INSERT INTO public.projects (title, description, location, date, organization_id) VALUES
-- Tech Relief (ID 1)
('Clinic Wi-Fi Setup', 'Installing mesh networks.', '{"Rural Clinic A"}', '2026-04-01', 1),
('Database Cleanup', 'Optimizing patient records.', '{"Remote"}', '2026-04-15', 1),
('Hardware Donation', 'Refurbishing 20 laptops.', '{"Tech Hub"}', '2026-05-01', 1),
('Security Audit', 'Reviewing firewall logs.', '{"Regional Office"}', '2026-05-10', 1),
('Staff Training', 'Teaching basic IT skills.', '{"Community Center"}', '2026-05-20', 1);

-- Ocean Watch (ID 2)
INSERT INTO public.projects (title, description, location, date, organization_id) VALUES
('Reef Survey', 'Diving to monitor coral health.', '{"Blue Bay"}', '2026-06-05', 2),
('Beach Clean-up', 'Removing microplastics.', '{"North Shore"}', '2026-06-12', 2),
('Turtle Protection', 'Nesting site monitoring.', '{"Hidden Cove"}', '2026-07-01', 2),
('Water Testing', 'Measuring salinity and pH.', '{"South Pier"}', '2026-07-15', 2),
('Public Webinar', 'Educating on ocean pollution.', '{"Online"}', '2026-08-01', 2);

INSERT INTO public.projects (title, description, location, date, organization_id) VALUES
('Downtown Mural', 'Painting a 3-story mural.', '{"Market St"}', '2026-04-20', 3),
('Youth Choir', 'After-school music lessons.', '{"District 5 Center"}', '2026-05-05', 3),
('Street Performance', 'Weekend jazz festival.', '{"Central Plaza"}', '2026-05-18', 3),
('Gallery Night', 'Showing local student art.', '{"Urban Gallery"}', '2026-06-10', 3),
('Instrument Drive', 'Collecting used guitars.', '{"High School"}', '2026-06-25', 3);

SELECT 
    o.name AS organization_name, 
    p.title AS project_title, 
    p.date
FROM public.organization o
JOIN public.projects p ON o.organization_id = p.organization_id
ORDER BY o.name;





